kind = "DojoModel"
class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
original_class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
abi = "manifests/dev/base/abis/models/diamond_pit-PlayerStats-20bc78b8.json"
tag = "diamond_pit-PlayerStats"
manifest_name = "diamond_pit-PlayerStats-20bc78b8"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "backpack_level"
type = "u8"
key = false

[[members]]
name = "pickaxe_level"
type = "u8"
key = false

[[members]]
name = "rebirth"
type = "u16"
key = false

[[members]]
name = "next_daily_coin"
type = "u64"
key = false
